/**
 * Task execution lifecycle status.
 * 
 * - `pending`: Task queued but not yet started
 * - `running`: Task currently executing
 * - `completed`: Task finished successfully
 * - `failed`: Task encountered an error
 * - `cancelled`: Task was cancelled by user
 */
export type TaskStatus = "pending" | "running" | "completed" | "failed" | "cancelled";

/**
 * Configuration for task execution.
 * 
 * Controls model selection, execution limits, tool permissions, and working directory.
 */
export interface TaskConfig {
  /** Model identifier (e.g., "claude-sonnet-4-5") */
  model?: string;
  
  /** Custom system prompt to prepend to conversation */
  systemPrompt?: string;
  
  /** Maximum conversation turns before automatic termination */
  maxTurns?: number;
  
  /** Budget limit in USD to prevent excessive API costs */
  maxBudgetUsd?: number;
  
  /** Whitelist of tool names the agent can use (empty = all allowed) */
  allowedTools?: string[];
  
  /** Permission handling mode:
   * - `default`: Prompt user for tool approvals
   * - `acceptEdits`: Auto-approve edit/write operations
   * - `bypassPermissions`: Auto-approve all operations (dangerous)
   */
  permissionMode?: "default" | "acceptEdits" | "bypassPermissions";
  
  /** Working directory for file operations and shell commands */
  cwd?: string;
}

/**
 * Attachment to include with a task prompt.
 * 
 * Supports files (path), images (base64), and URLs.
 */
export interface TaskAttachment {
  /** Attachment type */
  type: "file" | "image" | "url";
  
  /** File path, base64-encoded data, or URL string */
  content: string;
  
  /** MIME type for proper interpretation (e.g., "image/png") */
  mimeType?: string;
}

/**
 * A task represents a single agent execution request with full lifecycle tracking.
 * 
 * Tasks persist through the execution lifecycle, capturing:
 * - Configuration and prompt
 * - Status transitions (pending → running → completed/failed)
 * - All events (tool calls, text generation, errors)
 * - Cost and performance metrics
 */
export interface Task {
  /** Unique task identifier (generated server-side) */
  id: string;
  
  /** User's natural language prompt */
  prompt: string;
  
  /** Execution configuration */
  config: TaskConfig;
  
  /** Current lifecycle status */
  status: TaskStatus;
  
  /** Task creation timestamp */
  createdAt: Date;
  
  /** Execution start timestamp (set when status → running) */
  startedAt?: Date;
  
  /** Execution end timestamp (set when status → completed/failed/cancelled) */
  completedAt?: Date;
  
  /** Error message if status === 'failed' */
  error?: string;
  
  /** Execution results and metrics (populated on completion) */
  result?: TaskResult;
  
  /** Ordered stream of events produced during execution */
  events: TaskEvent[];
  
  /** Optional files, images, or URLs attached to the prompt */
  attachments?: TaskAttachment[];
}

/**
 * Summary of task execution results.
 * 
 * Captured upon task completion for performance tracking and billing.
 */
export interface TaskResult {
  /** Whether task completed without errors */
  success: boolean;
  
  /** Total execution time in milliseconds */
  durationMs: number;
  
  /** Total API cost in USD (based on token usage) */
  totalCostUsd: number;
  
  /** Number of assistant turns (back-and-forth exchanges) */
  numTurns: number;
  
  /** Token consumption breakdown */
  usage: {
    /** Input tokens sent to model */
    inputTokens: number;
    
    /** Output tokens generated by model */
    outputTokens: number;
  };
}

/**
 * Types of events that can occur during task execution.
 * 
 * Events are emitted in real-time via SSE and stored in task history.
 */
export type TaskEventType =
  /** Task execution started */
  | "started"
  
  /** Incremental text from assistant (streaming) */
  | "text_delta"
  
  /** Complete assistant message */
  | "assistant_message"
  
  /** System notification or status message */
  | "system_message"
  
  /** Agent initiated a tool call */
  | "tool_use"
  
  /** Tool execution result */
  | "tool_result"
  
  /** Waiting for user input (e.g., permission request) */
  | "user_input"
  
  /** Task completed successfully */
  | "completed"
  
  /** Task failed with error */
  | "failed"
  
  /** Task cancelled by user */
  | "cancelled"
  
  /** Agent requesting tool permission from user */
  | "permission_request"
  
  /** List of available slash commands from agent stderr */
  | "available_commands"
  
  /** Raw output from agent process (stderr) */
  | "agent_output";

/**
 * A single event in the task execution stream.
 * 
 * Events are immutable records of state changes, tool calls, and generated content.
 */
export interface TaskEvent {
  /** Unique event identifier */
  id: string;
  
  /** Event type discriminator */
  type: TaskEventType;
  
  /** Event creation timestamp */
  timestamp: Date;
  
  /** Event-specific payload (structure varies by type) */
  data: unknown;
}

/**
 * Request to create and execute a new task.
 * 
 * Sent via `POST /rpc` with method `session/prompt`.
 */
export interface CreateTaskRequest {
  /** Natural language prompt for the agent */
  prompt: string;
  
  /** Optional execution configuration (defaults applied if omitted) */
  config?: TaskConfig;
}

/**
 * User input response (e.g., answering agent question or providing permission).
 */
export interface UserInputRequest {
  /** User's response text */
  input: string;
}
